# Generated by Django 2.2.2 on 2019-07-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'date')},
        ),
    ]
