# Generated by Django 2.2.2 on 2019-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190702_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(null=True, to='core.Observer'),
        ),
    ]
